import { retryDocumentProcessingAction } from "@/app/document-actions";
import { DocumentProcessingStatus, UserRole } from "@/lib/generated/prisma/client";
import { db } from "@/lib/db";
import { requireUser } from "@/lib/session";
import { redirect } from "next/navigation";

export default async function DocumentAdministrationPage() {
  const user = await requireUser(); if (user.role !== UserRole.SYSTEM_ADMIN) redirect("/dashboard");
  const [counts, documents] = await Promise.all([db.attachment.groupBy({ by: ["processingStatus"], _count: true }), db.attachment.findMany({ include: { correspondence: { select: { referenceNumber: true } }, documentEvents: { orderBy: { createdAt: "desc" }, take: 1 } }, orderBy: { createdAt: "desc" }, take: 100 })]);
  return <><span className="eyebrow">Document security</span><h1>Quarantine and processing</h1><p className="muted">Only documents marked Available and Clean can be downloaded. Processing is performed by the protected worker.</p><div className="stats-grid">{counts.map((item) => <div className="stat-card" key={item.processingStatus}><small>{item.processingStatus}</small><strong>{item._count}</strong></div>)}</div><section className="card" style={{ marginTop: 18 }}><table className="table"><thead><tr><th>Document</th><th>State</th><th>Security</th><th>Processing</th><th>Control</th></tr></thead><tbody>{documents.map((item) => <tr key={item.id}><td><strong>{item.originalName}</strong><small className="registry-secondary">{item.correspondence.referenceNumber} · SHA-256 {item.sha256.slice(0, 12)}…</small></td><td>{item.processingStatus}<small className="registry-secondary">OCR {item.ocrStatus}</small></td><td>{item.malwareScanStatus}<small className="registry-secondary">{item.detectedMimeType ?? "Signature pending"}</small></td><td>{item.processingAttempts} attempt(s)<small className="registry-secondary">{item.processingError ?? item.documentEvents[0]?.detail ?? "Awaiting worker"}</small></td><td>{item.processingStatus !== DocumentProcessingStatus.PROCESSING && item.processingStatus !== DocumentProcessingStatus.AVAILABLE ? <form action={retryDocumentProcessingAction}><input type="hidden" name="attachmentId" value={item.id} /><button className="btn secondary compact">Retry</button></form> : "—"}</td></tr>)}{!documents.length ? <tr><td colSpan={5}>No document records.</td></tr> : null}</tbody></table></section></>;
}
