"use server";

import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { CorrespondenceType, Priority, UserRole, WorkflowTemplateVersionStatus, WorkPurpose } from "@/lib/generated/prisma/client";
import { db } from "@/lib/db";
import { requireUser } from "@/lib/session";
import { simulateWorkflow, workflowRulesSchema } from "@/lib/workflow-templates";

async function administrator() { const user = await requireUser(); if (user.role !== UserRole.SYSTEM_ADMIN) throw new Error("Only a system administrator can manage workflow policies."); return user; }

export async function createWorkflowVersionAction(formData: FormData) {
  const user = await administrator(); const templateId = String(formData.get("templateId") ?? ""); const reason = String(formData.get("reason") ?? "").trim();
  const rules = workflowRulesSchema.safeParse({ routingMode: "HIERARCHICAL", allowPeerReferral: formData.get("allowPeerReferral") === "on", allowedPurposes: formData.getAll("allowedPurposes").map(String), requireApprovalForOutgoing: formData.get("requireApprovalForOutgoing") === "on" });
  if (!rules.success || reason.length < 10 || reason.length > 500) redirect("/admin/workflows?error=validation");
  await db.$transaction(async (tx) => { const template = await tx.workflowTemplate.findUnique({ where: { id: templateId } }); if (!template) throw new Error("Workflow template not found."); const latest = await tx.workflowTemplateVersion.aggregate({ where: { templateId }, _max: { version: true } }); const created = await tx.workflowTemplateVersion.create({ data: { templateId, version: (latest._max.version ?? 0) + 1, rules: rules.data, changeReason: reason, createdById: user.id } }); await tx.configurationChange.create({ data: { setting: `workflowTemplate:${template.slug}`, previousValue: "", newValue: JSON.stringify({ version: created.version, status: created.status, rules: rules.data }), reason, changedById: user.id } }); });
  revalidatePath("/admin/workflows"); redirect("/admin/workflows?created=1");
}

export async function activateWorkflowVersionAction(formData: FormData) {
  const user = await administrator(); const versionId = String(formData.get("versionId") ?? ""); const reason = String(formData.get("reason") ?? "").trim(); if (reason.length < 10 || reason.length > 500) redirect("/admin/workflows?error=validation");
  const result = await db.$transaction(async (tx) => { const version = await tx.workflowTemplateVersion.findUnique({ where: { id: versionId }, include: { template: true } }); if (!version || version.status !== WorkflowTemplateVersionStatus.DRAFT) return false; workflowRulesSchema.parse(version.rules); const now = new Date(); await tx.workflowTemplateVersion.updateMany({ where: { templateId: version.templateId, status: WorkflowTemplateVersionStatus.ACTIVE }, data: { status: WorkflowTemplateVersionStatus.RETIRED, retiredAt: now } }); await tx.workflowTemplateVersion.update({ where: { id: version.id }, data: { status: WorkflowTemplateVersionStatus.ACTIVE, activatedAt: now, activatedById: user.id } }); await tx.configurationChange.create({ data: { setting: `workflowActivation:${version.template.slug}`, previousValue: "active predecessor", newValue: JSON.stringify({ version: version.version }), reason, changedById: user.id } }); return true; });
  if (!result) redirect("/admin/workflows?error=stale"); revalidatePath("/admin/workflows"); redirect("/admin/workflows?activated=1");
}

export async function updateWorkflowCategoryAction(formData: FormData) {
  const user = await administrator(); const id = String(formData.get("categoryId") ?? ""); const parsed = z.object({ version: z.coerce.number().int().positive(), routineSlaDays: z.coerce.number().int().min(1).max(365), urgentSlaDays: z.coerce.number().int().min(1).max(365), immediateSlaDays: z.coerce.number().int().min(1).max(365), reason: z.string().trim().min(10).max(500) }).safeParse({ version: formData.get("version"), routineSlaDays: formData.get("routineSlaDays"), urgentSlaDays: formData.get("urgentSlaDays"), immediateSlaDays: formData.get("immediateSlaDays"), reason: formData.get("reason") }); if (!parsed.success || parsed.data.immediateSlaDays > parsed.data.urgentSlaDays || parsed.data.urgentSlaDays > parsed.data.routineSlaDays) redirect("/admin/workflows?error=validation");
  const changed = await db.$transaction(async (tx) => { const current = await tx.workflowCategory.findUnique({ where: { id } }); if (!current || current.version !== parsed.data.version) return false; const updated = await tx.workflowCategory.updateMany({ where: { id, version: parsed.data.version }, data: { routineSlaDays: parsed.data.routineSlaDays, urgentSlaDays: parsed.data.urgentSlaDays, immediateSlaDays: parsed.data.immediateSlaDays, isActive: formData.get("isActive") === "on", version: { increment: 1 }, updatedById: user.id } }); if (!updated.count) return false; await tx.configurationChange.create({ data: { setting: `workflowCategory:${current.code}`, previousValue: JSON.stringify({ routineSlaDays: current.routineSlaDays, urgentSlaDays: current.urgentSlaDays, immediateSlaDays: current.immediateSlaDays, isActive: current.isActive }), newValue: JSON.stringify(parsed.data), reason: parsed.data.reason, changedById: user.id } }); return true; }); if (!changed) redirect("/admin/workflows?error=stale"); revalidatePath("/admin/workflows"); redirect("/admin/workflows?category=1");
}

export async function createWorkflowCategoryAction(formData: FormData) { const user = await administrator(); const parsed = z.object({ code: z.string().trim().regex(/^[A-Z][A-Z0-9_]{2,39}$/), name: z.string().trim().min(3).max(100), description: z.string().trim().min(10).max(500), correspondenceType: z.enum(CorrespondenceType), templateId: z.string().min(1), routineSlaDays: z.coerce.number().int().min(1).max(365), urgentSlaDays: z.coerce.number().int().min(1).max(365), immediateSlaDays: z.coerce.number().int().min(1).max(365), reason: z.string().trim().min(10).max(500) }).safeParse(Object.fromEntries(formData)); if (!parsed.success || parsed.data.immediateSlaDays > parsed.data.urgentSlaDays || parsed.data.urgentSlaDays > parsed.data.routineSlaDays) redirect("/admin/workflows?error=validation"); await db.$transaction(async (tx) => { const created = await tx.workflowCategory.create({ data: { code: parsed.data.code, name: parsed.data.name, description: parsed.data.description, correspondenceType: parsed.data.correspondenceType, templateId: parsed.data.templateId, routineSlaDays: parsed.data.routineSlaDays, urgentSlaDays: parsed.data.urgentSlaDays, immediateSlaDays: parsed.data.immediateSlaDays, updatedById: user.id } }); await tx.configurationChange.create({ data: { setting: `workflowCategory:${created.code}`, previousValue: "", newValue: JSON.stringify({ id: created.id, ...parsed.data }), reason: parsed.data.reason, changedById: user.id } }); }); revalidatePath("/admin/workflows"); redirect("/admin/workflows?category=1"); }

export async function simulateWorkflowAction(formData: FormData) { await administrator(); const parsed = z.object({ type: z.enum(CorrespondenceType), priority: z.enum(Priority), purpose: z.enum(WorkPurpose), categoryCode: z.string().trim().optional() }).safeParse({ type: formData.get("type"), priority: formData.get("priority"), purpose: formData.get("purpose"), categoryCode: formData.get("categoryCode") || undefined }); if (!parsed.success) redirect("/admin/workflows?error=validation"); const result = await simulateWorkflow(parsed.data); const query = new URLSearchParams({ simulated: "1", category: result.categoryCode, version: String(result.version), due: result.dueAt.toISOString(), sla: String(result.slaDays), approval: String(result.requiresApproval), peer: String(result.peerReferralAllowed), safe: String(result.safe) }); redirect(`/admin/workflows?${query}`); }
