import { redirect } from "next/navigation";
import { updateAssuranceCheckAction } from "@/app/assurance-actions";
import { AssuranceStatus, UserRole } from "@/lib/generated/prisma/client";
import { readinessSnapshot } from "@/lib/assurance";
import { db } from "@/lib/db";
import { requireUser } from "@/lib/session";

export const dynamic = "force-dynamic";
export default async function AssurancePage() {
  const user = await requireUser(); if (user.role !== UserRole.SYSTEM_ADMIN) redirect("/dashboard");
  const [checks, events, readiness] = await Promise.all([db.assuranceCheck.findMany({ orderBy: [{ category: "asc" }, { title: "asc" }] }), db.operationalEvent.findMany({ orderBy: { createdAt: "desc" }, take: 25 }), readinessSnapshot()]);
  const passed = checks.filter((check) => check.status === AssuranceStatus.PASSED).length;
  return <><span className="eyebrow">S26 production gate</span><h1>Assurance and pilot readiness</h1><p className="muted">Production is ready only when every required control has current evidence and the production configuration has no gaps.</p><div className="stats-grid"><div className="stat-card"><small>Evidence passed</small><strong>{passed}/{checks.length}</strong></div><div className="stat-card"><small>Unresolved gates</small><strong>{readiness.assurance.unresolved}</strong></div><div className="stat-card"><small>Configuration gaps</small><strong>{readiness.configurationIssues.length}</strong></div><div className="stat-card"><small>Production status</small><strong>{readiness.productionReady ? "READY" : "NOT READY"}</strong></div></div>{readiness.configurationIssues.length ? <section className="card" style={{ marginTop: 18 }}><h2>Configuration gaps</h2><ul>{readiness.configurationIssues.map((issue) => <li key={issue}>{issue}</li>)}</ul></section> : null}<section className="card" style={{ marginTop: 18 }}><h2>Required evidence register</h2>{checks.map((check) => <details key={check.id} style={{ marginBottom: 14 }}><summary><strong>{check.title}</strong> · {check.status} · {check.category}</summary><p className="muted">{check.description}</p><form action={updateAssuranceCheckAction} className="form-grid"><input type="hidden" name="id" value={check.id}/><label>Status<select name="status" defaultValue={check.status}>{Object.values(AssuranceStatus).map((status) => <option key={status}>{status}</option>)}</select></label><label>Accountable owner<input name="owner" defaultValue={check.owner ?? ""} required /></label><label>Evidence expiry<input type="date" name="expiresAt" defaultValue={check.expiresAt?.toISOString().slice(0, 10) ?? ""}/></label><label className="full-width">Evidence, test report, ticket or decision reference<textarea name="evidence" defaultValue={check.evidence ?? ""} required minLength={10}/></label><button className="btn" type="submit">Record review</button></form></details>)}</section><section className="card" style={{ marginTop: 18 }}><h2>Recent operational events</h2><table className="table"><thead><tr><th>Time</th><th>Severity</th><th>Component</th><th>Event</th></tr></thead><tbody>{events.map((event) => <tr key={event.id}><td>{event.createdAt.toLocaleString()}</td><td>{event.severity}</td><td>{event.component}</td><td>{event.message}</td></tr>)}{!events.length ? <tr><td colSpan={4}>No operational events recorded.</td></tr> : null}</tbody></table></section></>;
}
