ALTER TYPE "CorrespondenceStatus" ADD VALUE 'DRAFT' BEFORE 'SUBMITTED';

ALTER TYPE "EventType" ADD VALUE 'DRAFTED' BEFORE 'SUBMITTED';
ALTER TYPE "EventType" ADD VALUE 'DRAFT_UPDATED' BEFORE 'SUBMITTED';
ALTER TYPE "EventType" ADD VALUE 'DRAFT_DELETED' BEFORE 'SUBMITTED';

ALTER TABLE "Correspondence"
ADD COLUMN "draftActionRecipientIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "draftCopyRecipientIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "draftInstruction" TEXT;
