import { redirect } from "next/navigation";
import { activateWorkflowVersionAction, createWorkflowCategoryAction, createWorkflowVersionAction, simulateWorkflowAction, updateWorkflowCategoryAction } from "@/app/workflow-actions";
import { UserRole, WorkflowTemplateVersionStatus } from "@/lib/generated/prisma/client";
import { db } from "@/lib/db";
import { requireUser } from "@/lib/session";

export default async function WorkflowAdministrationPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const user = await requireUser(); if (user.role !== UserRole.SYSTEM_ADMIN) redirect("/dashboard"); const query = await searchParams;
  const [templates, categories] = await Promise.all([db.workflowTemplate.findMany({ include: { versions: { include: { createdBy: true, activatedBy: true }, orderBy: { version: "desc" } } } }), db.workflowCategory.findMany({ include: { template: true, updatedBy: true }, orderBy: { code: "asc" } })]);
  return <><span className="eyebrow">Controlled configuration</span><h1>Workflow templates and SLAs</h1><p className="muted">Create immutable draft versions, activate one version per template, configure business-day SLAs and simulate policy without changing live work.</p>
    {query.error ? <p className="notice error">The request was invalid or stale. Refresh and review the policy values.</p> : null}{query.created || query.activated || query.category ? <p className="notice success">Workflow configuration updated and audited.</p> : null}
    {query.simulated ? <section className={`notice ${query.safe === "true" ? "success" : "error"}`}><strong>Simulation: {query.safe === "true" ? "permitted" : "blocked"}</strong><br />Category {query.category} · template v{query.version} · {query.sla} business days · due {new Date(query.due!).toLocaleDateString("en-NG")} · approval {query.approval === "true" ? "required" : "not automatic"} · peer referral {query.peer === "true" ? "allowed" : "blocked"}</section> : null}
    <section className="card"><h2>Safe simulation</h2><form action={simulateWorkflowAction} className="form-grid"><div className="field"><label>Type</label><select name="type"><option>INCOMING_LETTER</option><option>OUTGOING_LETTER</option><option>INTERNAL_MEMO</option></select></div><div className="field"><label>Priority</label><select name="priority"><option>ROUTINE</option><option>URGENT</option><option>IMMEDIATE</option></select></div><div className="field"><label>Purpose</label><select name="purpose"><option>ACTION</option><option>REVIEW</option><option>CONCURRENCE</option><option>APPROVAL</option></select></div><div className="field"><label>Category code (optional)</label><input name="categoryCode" /></div><button className="btn span-2">Simulate without creating work</button></form></section>
    <div className="grid" style={{ gridTemplateColumns: "repeat(auto-fit,minmax(360px,1fr))", marginTop: 18 }}>{templates.map((template) => <section className="card" key={template.id}><span className="eyebrow">{template.slug}</span><h2>{template.name}</h2><p>{template.description}</p>{template.versions.map((version) => <div className="handler-strip" key={version.id}><div><strong>Version {version.version} · {version.status}</strong><small>{version.changeReason} · {version.createdAt.toLocaleString("en-NG")}</small></div>{version.status === WorkflowTemplateVersionStatus.DRAFT ? <form action={activateWorkflowVersionAction}><input type="hidden" name="versionId" value={version.id} /><input name="reason" required minLength={10} placeholder="Activation reason" /><button className="btn compact">Activate</button></form> : null}</div>)}<h3>Create immutable draft</h3><form action={createWorkflowVersionAction} className="grid"><input type="hidden" name="templateId" value={template.id} />{["ACTION","REVIEW","CONCURRENCE","APPROVAL"].map((purpose) => <label className="check-field" key={purpose}><input type="checkbox" name="allowedPurposes" value={purpose} defaultChecked /><span>{purpose}</span></label>)}<label className="check-field"><input type="checkbox" name="allowPeerReferral" defaultChecked /><span>Allow controlled peer referral</span></label><label className="check-field"><input type="checkbox" name="requireApprovalForOutgoing" defaultChecked /><span>Require outgoing approval</span></label><div className="field"><label>Version reason</label><textarea name="reason" minLength={10} required /></div><button className="btn secondary">Create draft version</button></form></section>)}</div>
    <section className="card" style={{ marginTop: 18 }}><h2>Category SLA policies</h2>{categories.map((category) => <form action={updateWorkflowCategoryAction} className="handler-strip" key={category.id}><input type="hidden" name="categoryId" value={category.id} /><input type="hidden" name="version" value={category.version} /><div><strong>{category.code} · {category.name}</strong><small>{category.correspondenceType} · {category.template.name} · version {category.version}</small><div className="actions"><label>Routine <input name="routineSlaDays" type="number" min="1" max="365" defaultValue={category.routineSlaDays} /></label><label>Urgent <input name="urgentSlaDays" type="number" min="1" max="365" defaultValue={category.urgentSlaDays} /></label><label>Immediate <input name="immediateSlaDays" type="number" min="1" max="365" defaultValue={category.immediateSlaDays} /></label></div><input name="reason" minLength={10} required placeholder="Reason for SLA change" /></div><div><label><input type="checkbox" name="isActive" defaultChecked={category.isActive} /> Active</label><button className="btn secondary compact">Save</button></div></form>)}</section>
    <section className="card" style={{ marginTop: 18 }}><h2>Create category</h2><form action={createWorkflowCategoryAction} className="form-grid"><div className="field"><label>Code</label><input name="code" pattern="[A-Z][A-Z0-9_]{2,39}" required /></div><div className="field"><label>Name</label><input name="name" minLength={3} required /></div><div className="field span-2"><label>Description</label><input name="description" minLength={10} required /></div><div className="field"><label>Type</label><select name="correspondenceType"><option>INCOMING_LETTER</option><option>OUTGOING_LETTER</option><option>INTERNAL_MEMO</option></select></div><div className="field"><label>Template</label><select name="templateId">{templates.map((template) => <option key={template.id} value={template.id}>{template.name}</option>)}</select></div><div className="field"><label>Routine days</label><input name="routineSlaDays" type="number" min="1" max="365" defaultValue="10" required /></div><div className="field"><label>Urgent days</label><input name="urgentSlaDays" type="number" min="1" max="365" defaultValue="5" required /></div><div className="field"><label>Immediate days</label><input name="immediateSlaDays" type="number" min="1" max="365" defaultValue="2" required /></div><div className="field span-2"><label>Reason</label><input name="reason" minLength={10} required /></div><button className="btn span-2">Create category</button></form></section>
  </>;
}
