import { redirect } from "next/navigation";
import { addAccessGroupMemberAction, assignRecordAccessGroupAction, createAccessGroupAction, removeAccessGroupMemberAction, removeRecordAccessGroupAction } from "@/app/access-group-actions";
import { UserRole } from "@/lib/generated/prisma/client";
import { db } from "@/lib/db";
import { requireUser } from "@/lib/session";

export default async function AccessGroupsPage() {
  const actor = await requireUser(); if (actor.role !== UserRole.SYSTEM_ADMIN) redirect("/dashboard");
  const [users, groups, accessEvents] = await Promise.all([
    db.user.findMany({ where: { isActive: true }, orderBy: { name: "asc" }, take: 500 }),
    db.accessGroup.findMany({ include: { members: { include: { user: true } }, records: { include: { correspondence: true } }, createdBy: true }, orderBy: { name: "asc" } }),
    db.sensitiveAccessEvent.findMany({ include: { user: true, correspondence: true }, orderBy: { createdAt: "desc" }, take: 100 }),
  ]);
  return <><span className="eyebrow">Information barriers</span><h1>Need-to-know access</h1><p className="muted">A restricted record is available only to its originator and members of at least one assigned active group. Secret records additionally require eligible role and fresh step-up authentication.</p>
    <form action={createAccessGroupAction} className="card grid"><h2>Create access group</h2><label className="field"><span>Name</span><input name="name" required minLength={3} /></label><label className="field"><span>Purpose</span><textarea name="description" required minLength={10} /></label><div className="field"><span>Initial members</span><div className="access-member-grid">{users.map((user) => <label className="check-field" key={user.id}><input type="checkbox" name="memberIds" value={user.id} /><span>{user.name}<small>{user.email}</small></span></label>)}</div></div><button className="btn" type="submit">Create group</button></form>
    <div className="grid" style={{ marginTop: 18 }}>{groups.map((group) => <section className="card" key={group.id}><h2>{group.name}</h2><p>{group.description}</p><div>{group.members.map((item) => <form action={removeAccessGroupMemberAction} className="actions" key={item.userId}><input type="hidden" name="groupId" value={group.id} /><input type="hidden" name="userId" value={item.userId} /><span>{item.user.name}</span><input name="reason" required minLength={10} placeholder="Removal reason" /><button className="btn secondary compact">Remove</button></form>)}</div><div>{group.records.map((item) => <form action={removeRecordAccessGroupAction} className="actions" key={item.correspondenceId}><input type="hidden" name="groupId" value={group.id} /><input type="hidden" name="correspondenceId" value={item.correspondenceId} /><span>{item.correspondence.referenceNumber}</span><input name="reason" required minLength={10} placeholder="Unrestriction reason" /><button className="btn secondary compact">Unrestrict</button></form>)}</div><form action={addAccessGroupMemberAction} className="actions"><input type="hidden" name="groupId" value={group.id} /><select name="userId" required><option value="">Add member</option>{users.map((user) => <option key={user.id} value={user.id}>{user.name}</option>)}</select><button className="btn secondary compact">Add</button></form><form action={assignRecordAccessGroupAction} className="actions"><input type="hidden" name="groupId" value={group.id} /><input name="reference" required placeholder="ITF/FLOW/2026/00001" /><button className="btn secondary compact">Restrict record</button></form></section>)}</div>
    <section className="card" style={{ marginTop: 18 }}><h2>Sensitive-access report</h2><table className="table"><thead><tr><th>Time</th><th>User</th><th>Reference</th><th>Activity</th><th>Detail</th></tr></thead><tbody>{accessEvents.map((event) => <tr key={event.id}><td>{event.createdAt.toLocaleString("en-NG")}</td><td>{event.user.name}</td><td>{event.correspondence.referenceNumber}</td><td>{event.type}</td><td>{event.detail ?? "—"}</td></tr>)}{!accessEvents.length ? <tr><td colSpan={5}>No sensitive access recorded.</td></tr> : null}</tbody></table></section>
  </>;
}
